@echo off
echo [ANTIGRAVITY] Starting automated setup...
echo [ANTIGRAVITY] Cleaning old node_modules (this may take a moment)...
rmdir /s /q node_modules 2>nul
rmdir /s /q .next 2>nul
echo [ANTIGRAVITY] Installing dependencies...
call npm install --no-audit --no-fund --loglevel=error
echo [ANTIGRAVITY] Starting app...
call npm run dev
